/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD_Char_1.h"
#include "Filter.h"
#include "Filter_PVT.h"
#include "ADC_SAR_1.h"
#include "AUDIO_IN_aliases.h"
#include "AUDIO_IN.h"
#include "DIV_MUX_CONTROL_aliases.h"
#include "DIV_MUX_CONTROL.h"
#include "MASK_OFF_CONTROL_aliases.h"
#include "MASK_OFF_CONTROL.h"
#include "MOSI_OUT_aliases.h"
#include "MOSI_OUT.h"
#include "SAMPLE_RATE_CONTROL_aliases.h"
#include "SAMPLE_RATE_CONTROL.h"
#include "Opamp_1.h"
#include "VREF_BUFF_aliases.h"
#include "VREF_BUFF.h"
#include "SPI_DAC.h"
#include "SPI_DAC_PVT.h"
#include "MISO_IN_aliases.h"
#include "MISO_IN.h"
#include "SCLK_OUT_aliases.h"
#include "SCLK_OUT.h"
#include "SS_OUT_aliases.h"
#include "SS_OUT.h"
#include "Opamp_2.h"
#include "ADC_SAR_Seq.h"
#include "PWM_ADC_CK.h"
#include "ADC_REG_CLOCK.h"
#include "PWM_1_CONTROL_aliases.h"
#include "PWM_1_CONTROL.h"
#include "DIV_MASK_MSB.h"
#include "DIV_MASK_LSB.h"
#include "Bus_clock.h"
#include "ADC_1_OUT_MSB.h"
#include "ADC_1_OUT_LSB.h"
#include "DAC_IN_MSB.h"
#include "DAC_IN_LSB.h"
#include "SEQ_CLOCK.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "ADC_SAR_1_IRQ.h"
#include "SPI_DAC_IntClock.h"
#include "ADC_SAR_Seq_SAR.h"
#include "ADC_SAR_Seq_TempBuf_dma.h"
#include "ADC_SAR_Seq_FinalBuf_dma.h"
#include "ADC_SAR_Seq_IRQ.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

